var allcards = {"Abomination": {text: "Enter: Put mana on this equal to the total amount of mana on creatures you control, then bind all creatures you control to this. This has all abilities of creatures bound to this.", cost: 6, type: "Creature", power: 6},
"Academy Mage": {text: "When a Sorcery you control deals damage to a creature or player, choose a creature or player and deal 3 damage to them.", cost: 3, type: "Creature", power: 3},
"Aggravated Rabbit": {text: "Hits a player: Create a copy of this.", cost: 4, type: "Creature", power: 1},
"All In": {text: "Destroy all spells in your Archive. Distribute three mana.", cost: 0, type: "Sorcery", power: ""},
"Angel of Eternity": {text: "Other creatures can't be damaged or destroyed.", cost: 8, type: "Creature", power: 8},
"Angel of Triumph": {text: "You can't lose the game.", cost: 7, type: "Creature", power: 7},
"Archaeologist": {text: "You may treat all spells in your Void as if they were in your Archive and all spells in your Archive as if they were in your Void.", cost: 6, type: "Creature", power: 3},
"Arm": {text: "Choose a creature and put five mana on it.", cost: 3, type: "Sorcery", power: ""},
"Arrest": {text: "Choose a creature, then choose a creature you control. Bind the first to the second.", cost: 1, type: "Sorcery", power: ""},
"Aspiring Squire": {text: "Hits a player: The amount of mana on this becomes 8.", cost: 3, type: "Creature", power: 1},
"Assemble": {text: "Create three Conscript creatures with ! 2.", cost: 5, type: "Sorcery", power: ""},
"Avatar of the Fifth Gate": {text: "Dies: Take a turn.", cost: 9, type: "Creature", power: 9},
"Avatar of the Second Gate": {text: "When another creature would leave the Battlefield, instead bind it to this creature.", cost: 9, type: "Creature", power: 9},
"Battlesculpt": {text: "Your opponent divides all creatures into two piles face up. Choose a pile and destroy all creatures in that pile.", cost: 4, type: "Sorcery", power: ""},
"Bless": {text: "Choose a creature and put ten mana on it.", cost: 6, type: "Sorcery", power: ""},
"Blood Artist": {text: "Hits a player: Distribute one mana.", cost: 1, type: "Creature", power: 1},
"Bloodcaster": {text: "Hits a player: Choose a Sorcery spell with $ X in your Archive, where X is the ! of this. Destroy it and copy its effects.", cost: 1, type: "Creature", power: 1},
"Bloodfire": {text: "Choose a creature. Pay any amount of life and deal that much damage to that creature.", cost: 2, type: "Sorcery", power: ""},
"Blooming Flower": {text: "Start of each Execution: Put one mana on this.", cost: 2, type: "Creature", power: 1},
"Boar Ring": {text: "Create two Boars with ! 4. Your opponent creates a Boar with ! 4.", cost: 4, type: "Sorcery", power: ""},
"Brave Salvager": {text: "Hits a player: That player chooses a spell in their Void. You put that spell into your Archive.", cost: 4, type: "Creature", power: 3},
"Brawler": {text: "Start of each Execution: Choose a creature. This deals damage equal to its ! to that creature and that creature deals damage equal to its ! to this.", cost: 4, type: "Creature", power: 4},
"Breach Thoughts": {text: "Choose a creature, then choose two spells in Archives and bind them to that creature.", cost: 4, type: "Sorcery", power: ""},
"Call to Congregation": {text: "Choose any number of creatures spells in your Archive with total $ equal to the total ! of creatures you control and put them onto the battlefield.", cost: 5, type: "Sorcery", power: ""},
"Caller of the Wild Storm": {text: "The $s of Creature spells in your Spellbook are reduced by 3. At the end of your turn, choose three creatures you control and put them into your Spellbook.", cost: 6, type: "Creature", power: 3},
"Calm": {text: "Exhaust all creatures. The next time they would unexhaust, they don't.", cost: 2, type: "Sorcery", power: ""},
"Champion of Libraries": {text: "Start of each Execution: The amount of mana on this becomes equal to X, where X is the number of spells in your Archive.", cost: 2, type: "Creature", power: 1},
"Champion of Thoughts": {text: "Start of each Execution: The amount of mana on this becomes equal to X, where X is the number of spells in your Spellbook.", cost: 2, type: "Creature", power: 1},
"Charge": {text: "Each refreshed creature attacks (in any order). (You don't need to exhaust them.)", cost: 7, type: "Sorcery", power: ""},
"Charging Vanguard": {text: "When another creature enters the battlefield under your control, this attacks. (You don't need to exhaust this.)", cost: 5, type: "Creature", power: 4},
"Charmer": {text: "Enter: Choose a creature and gain control of it. Leave: That creature's owner gains control of that creature.", cost: 7, type: "Creature", power: 3},
"Chef": {text: "Start of your Execution: Choose one -  - Choose another creature. Put two mana on it. - Choose a player. They gain 4 life.", cost: 4, type: "Creature", power: 2},
"Chosen One": {text: "This must be chosen if able by spells or abilities (while on the Battlefield).", cost: 4, type: "Creature", power: 4},
"Clumsy Excavator": {text: "Start of your Execution: Choose three spells in your Archive and destroy them. If you do, your opponent chooses a spell in your Void. Put that spell into your Spellbook.", cost: 5, type: "Creature", power: 3},
"Combustible Lemon": {text: "In your Void: When you Shift: Put this into your Spellbook.", cost: 0, type: "Sorcery", power: ""},
"Combustible Memory": {text: "When this is Combusted, choose a spell in your Void and put it into your Archive.", cost: 5, type: "Sorcery", power: ""},
"Command of Undeath": {text: "Choose a creature. When it dies this turn, return it to the Battlefield under your control.", cost: 2, type: "Sorcery", power: ""},
"Controlled Wrath": {text: "Destroy all creatures with ! X-1.", cost: "X", type: "Sorcery", power: ""},
"Counterspell": {text: "Choose a spell in the Plan and put it into its owner's Archive.", cost: 3, type: "Sorcery", power: ""},
"Cult Leader": {text: "End of your turn: Distribute X mana, where X is the number of creatures that died this turn.", cost: 5, type: "Creature", power: 3},
"Cursed Cultist": {text: "Dies: Create a Horror creature with ! 10.", cost: 5, type: "Creature", power: 1},
"Cursed Spud": {text: "Put this into your opponent's Spellbook. In your Spellbook: Start of your Execution: Deal 3 damage to yourself.", cost: 3, type: "Sorcery", power: ""},
"Cursed Wanderer": {text: "Dies: Create a Zombie creature with ! 3.", cost: 2, type: "Creature", power: 1},
"Dark Cultist": {text: "Dies: Choose a Creature spell in your Void and put it onto the Battlefield.", cost: 4, type: "Creature", power: 1},
"Decinimancer": {text: "Leave: Each other creature's ! becomes 10.", cost: 10, type: "Creature", power: 10},
"Decrypt": {text: "Each player puts all spells in their Void into their Spellbook.", cost: 8, type: "Sorcery", power: ""},
"Deranged Jailer": {text: "Enter: Choose a creature and bind it to this. Start of your Execution: Swap two bound spells.", cost: 5, type: "Creature", power: 3},
"Despairing Soul": {text: "For all spell effects and abilities, instead of your opponent, you are your own opponent.", cost: 4, type: "Creature", power: 4},
"Desperate Conscription": {text: "Create a Recruit creature with ! 1. Then, if your opponent controls more creatures than you, repeat this process.", cost: 2, type: "Sorcery", power: ""},
"Devoted Muse": {text: "Start of each Execution: Distribute one mana.", cost: 4, type: "Creature", power: 2},
"Disjoint": {text: "Choose a spell in the Plan and put it into its owner's Spellbook.", cost: 1, type: "Sorcery", power: ""},
"Doctor": {text: "When this would deal damage to a player, you may have that player gain that much life instead. When this would deal damage to a creature, you may put that much mana on that creature instead.", cost: 1, type: "Creature", power: 1},
"Dragon-Reaper": {text: "In your Spellbook: Start of your Execution: Choose a creature you control. Put mana on this equal to the ! of that creature, then destroy that creature.", cost: 16, type: "Creature", power: 16},
"Duck": {text: "Choose one -  - Create a Duck creature with ! 2. - Choose a creature or player. That creature or player can't be chosen this turn. (This applies to choosing attack targets, spells that choose, and abilities that choose.)", cost: 2, type: "Sorcery", power: ""},
"Eager Brawler": {text: "Enter: This attacks. (You don't need to exhaust this.)", cost: 4, type: "Creature", power: 4},
"Eager Soldier": {text: "When you Plan a spell, this attacks. (You don't need to exhaust this.)", cost: 3, type: "Creature", power: 3},
"Economist": {text: "Creatures you control deal damage equal to their $ rather than their !.", cost: 5, type: "Creature", power: 5},
"Explode": {text: "Choose a creature. It deals damage equal to its ! to each other creature and player. Destroy that creature.", cost: 6, type: "Sorcery", power: ""},
"Explosive Bunny": {text: "Dies: Choose a creature and destroy it.", cost: 3, type: "Creature", power: 1},
"Fiery Cultist": {text: "End of your turn: Choose a creature or player and deal X damage to them, where X is the number of creatures that died this turn.", cost: 4, type: "Creature", power: 2},
"Fight": {text: "Choose a creature you control and another creature. Each deals damage equal to their ! to the other.", cost: 0, type: "Sorcery", power: ""},
"Fire Faerie": {text: "Hits a player: Put this into the Plan.", cost: 5, type: "Sorcery", power: 2},
"Fireball": {text: "Choose a creature or player. Deal 6 damage to them.", cost: 6, type: "Sorcery", power: ""},
"Fireblast": {text: "Choose a creature or player and deal 1 damage to them.", cost: 1, type: "Sorcery", power: ""},
"Fireshaper": {text: 'Spells in the Plan lose all text and gain "Choose a creature and deal X damage to it, where X is the $ of this spell."', cost: 4, type: "Creature", power: 4},
"Firestorm": {text: "Deal X-1 damage to all creatures.", cost: "X", type: "Sorcery", power: ""},
"Flame Bolt": {text: "Choose a player and deal 3 damage to them.", cost: 1, type: "Sorcery", power: ""},
"Flame Jet": {text: "Choose a creature and deal X+1 damage to it.", cost: "X", type: "Sorcery", power: ""},
"Fleeting Inspiration": {text: "Choose a creature and create a copy of it. It attacks. (You don't need to exhaust the creature.) Destroy that creature at end of turn.", cost: 3, type: "Sorcery", power: ""},
"Flicker": {text: "Put all creatures into the Plan (in any order, keeping the amount of mana on them).", cost: 8, type: "Sorcery", power: ""},
"Formshaper": {text: 'When you would Execute a Sorcery spell, you may instead put it into your Void, create a Manifestation creature with ! 0 and "Dies: Copy the effects of all Sorcery spells bound to this", then bind the spell to the creature.', cost: 4, type: "Creature", power: 2},
"Frost Wyrm": {text: "You and your opponent skip your Increase subphases.", cost: 6, type: "Creature", power: 6},
"Genie": {text: 'Enter: Put three new Sorcery spells into your Spellbook named Wish that have $ X and have "Choose a spell with $ X-1 in your Archive and copy its effects." Leave: Destroy all Wishes in your Spellbook.', cost: 7, type: "Creature", power: 7},
"Giant": {text: "", cost: 8, type: "Creature", power: 12},
"Glimpser of Beauty": {text: "Start of your Execution: Distribute X mana, where X is the number of creatures you control.", cost: 7, type: "Creature", power: 2},
"Glimpser of Eternity": {text: "When this or another creature dies, its controller chooses a spell from their Void with lesser $ than that creature's $ and puts it into their Spellbook.", cost: 7, type: "Creature", power: 2},
"Golem": {text: "", cost: "X", type: "Creature", power: "X"},
"Grace": {text: "Until end of turn, prevent all damage that would be dealt.", cost: 0, type: "Sorcery", power: ""},
"Great General": {text: "When you Plan a Creature spell, create a Recruit creature with ! 1.", cost: 4, type: "Creature", power: 4},
"Great Wizard": {text: "When you Plan a Sorcery spell, create a Student creature with ! 1.", cost: 4, type: "Creature", power: 4},
"Grief Mage": {text: "When you Combust a spell, put it into your Archive from your Void, then bind it to this.", cost: 5, type: "Creature", power: 5},
"Griefkeeper": {text: "This has all abilities of all creature spells in your Void.", cost: 5, type: "Creature", power: 2},
"Grow": {text: "You gain one mana potential.", cost: 3, type: "Sorcery", power: ""},
"Guardian": {text: 'Start of each Execution: You may destroy this and have other creatures you control gain "Cannot be damaged or destroyed" until end of turn.', cost: 2, type: "Creature", power: 2},
"Harbinger of Wrath": {text: "Dies: Destroy all creatures.", cost: 1, type: "Creature", power: 1},
"Harvest": {text: "You gain 6 mana potential.", cost: 12, type: "Sorcery", power: ""},
"Illusion of Peace": {text: "Start of each Execution: Destroy the last spell in the Plan. If a spell was destroyed this way, destroy this.", cost: 2, type: "Creature", power: 3},
"Imaginary Friend": {text: "Enter: Choose a creature you control and put it into your Spellbook.", cost: 3, type: "Creature", power: 5},
"Implode": {text: "Choose a creature. Its controller chooses a player. The creature deals damage equal to its ! to the player. Destroy that creature.", cost: 3, type: "Sorcery", power: ""},
"Incorruptible Executioner": {text: "Enter and Leave: Each player chooses a creature they control and destroys it.", cost: 4, type: "Creature", power: 2},
"Infantry": {text: "", cost: 4, type: "Creature", power: 6},
"Inquisitor": {text: "Enter: Choose a spell in an Archive and bind it to this.", cost: 1, type: "Creature", power: 1},
"Inspire": {text: "Put one mana on each creature you control.", cost: 2, type: "Sorcery", power: ""},
"Inspiring Commander": {text: "Start of your Execution: Put one mana on each other creature you control.", cost: 5, type: "Creature", power: 3},
"Interrogate": {text: "Choose a spell in a Spellbook or Archive and a creature. Bind that spell to that creature.", cost: 1, type: "Sorcery", power: ""},
"Iron Automaton": {text: "If damage would be dealt to this, deal 2 damage to this instead.", cost: 6, type: "Creature", power: 6},
"Jailer": {text: "Enter: Choose a creature and bind it to this.", cost: 3, type: "Creature", power: 2},
"Keep in Mind": {text: "Choose a spell in your Void and put it into your Archive.", cost: 1, type: "Sorcery", power: ""},
"Kill": {text: "Choose a creature and destroy it.", cost: 3, type: "Sorcery", power: ""},
"Knight": {text: "", cost: 6, type: "Creature", power: 9},
"Lancer": {text: "When this would deal damage to a player, this deals twice that much damage instead.", cost: 1, type: "Creature", power: 1},
"Last Hurrah": {text: "Return all creatures with $ X from your Void to the Battlefield. At end of turn, destroy all creatures with $ X.", cost: "XX", type: "Sorcery", power: ""},
"Legionary": {text: "Enter: Put four mana on each creature you control with the same name as this.", cost: 4, type: "Creature", power: 1},
"Legionary's Cry": {text: "Choose a spell name, then put four mana on all spells with that name on the Battlefield or in a Spellbook.", cost: 7, type: "Sorcery", power: ""},
"Legislator": {text: "Enter: Choose a spell name, then bind all spells in any zone with that name to this. 2: ", cost: 3, type: "Creature", power: 2},
"Librarian": {text: "When you Shift: Choose a spell in your Void and put it into your Archive. Then, if you have twenty or more spells in your Archive, you win the game.", cost: 6, type: "Creature", power: 2},
"Lich": {text: "Enter: Choose a creature with ! 4 or less. Until that creature leaves the Battlefield, this can't be damaged or destroyed.", cost: 7, type: "Creature", power: 7},
"Lightning Bearer": {text: "Dies: Choose a creature or player and deal 3 damage to them.", cost: 2, type: "Creature", power: 1},
"Link": {text: "Choose two creatures. Bind one to the other.", cost: 3, type: "Sorcery", power: ""},
"Living Weapon": {text: "Choose a creature in your Spellbook. Put it onto the Battlefield. It attacks. (You don't need to exhaust the creature.) Destroy that creature when this turn ends.", cost: 6, type: "Sorcery", power: ""},
"Lord of the Undead": {text: "Creature spells in Voids may attack, be attacked, and have mana distributed to them as if they were on the Battlefield. (They still enter the Void with zero mana on them and their abilities still do not function.)", cost: 6, type: "Sorcery", power: 3},
"Loyal Hound": {text: "This doesn't deal damage unless you control another Attack action in the Plan.", cost: 1, type: "Creature", power: 2},
"Mad Scientist": {text: "When you Combust a spell, put mana on this equal to that spell's $.", cost: 2, type: "Creature", power: 1},
"Mage of Composure": {text: "Players don't lose the game unless their life is exactly 0. When damage would be dealt to a player with less than 0 life, that player gains that much life instead.", cost: 7, type: "Creature", power: 7},
"Magic-hungry Rampager": {text: "When you Plan a Sorcery spell, you may bind it to this. End of each turn: If this damaged a player this turn, copy the effects of all Sorcery spells bound to this.", cost: 2, type: "Creature", power: 1},
"Mana Bearer": {text: "Start of each Execution: X becomes the ! of this. Dies: Choose a creature you control and put X mana on it.", cost: 1, type: "Creature", power: 1},
"Mana Burst": {text: "Each player takes a Distribute subphase.", cost: 3, type: "Sorcery", power: ""},
"Mana Obliteration": {text: "Each player's mana potential becomes 1.", cost: 5, type: "Sorcery", power: ""},
"Mana Pulse": {text: "Put one mana on each spell in your Spellbook.", cost: 2, type: "Sorcery", power: ""},
"Mana Ritual": {text: "Distribute three mana.", cost: 2, type: "Sorcery", power: ""},
"Manabound Demon": {text: "Start of your Execution: Remove two mana from a spell in your Spellbook or destroy this.", cost: 3, type: "Creature", power: 6},
"Manabound Octopus": {text: "This doesn't deal damage unless you control a Sorcery spell in the Plan.", cost: 4, type: "Creature", power: 8},
"Manasmith": {text: "When any amount of mana would be put onto a creature, that much mana plus one is put onto that creature instead. (This applies to creatures entering the battlefield, including this creature.)", cost: 3, type: "Creature", power: 3},
"Mash": {text: "Choose two creatures the same player controls. Bind the first to the second, and the second gains the first's ! and text.", cost: 2, type: "Sorcery", power: ""},
"Memory Salvager": {text: "When this takes damage, choose a spell in your Void and put it into your Archive.", cost: 6, type: "Creature", power: 4},
"Mirage": {text: "Enter: You may choose another creature on the Battlefield and have this become a copy of it. (The ! of this remains unchanged.)", cost: 5, type: "Creature", power: 5},
"Mirrorblurrer": {text: 'This has all abilities of other creatures you control with the same !. Other creatures you control have "This has all abilities of other creatures you control with the same !."', cost: 4, type: "Creature", power: 2},
"Mirrorweave": {text: "Choose X spells in your Archive and destroy them. For each spell destroyed this way, choose a spell in your Archive and put a copy of it into your Archive.", cost: "X", type: "Sorcery", power: ""},
"Mist Mage": {text: "Start of your Execution: Choose a creature. Its controller puts it into their Spellbook.", cost: 6, type: "Creature", power: 6},
"Mistify": {text: "Choose a creature. Its controller puts it into their Spellbook.", cost: 3, type: "Sorcery", power: ""},
"Moon's Disdain": {text: "If it's your opponent's turn, choose a spell in the Plan and put it into its owner's Archive.", cost: 1, type: "Sorcery", power: ""},
"Moon's Revenge": {text: "Choose an exhausted creature and destroy it.", cost: 2, type: "Sorcery", power: ""},
"Moon's Wrath": {text: "Destroy all exhausted creatures.", cost: 4, type: "Sorcery", power: ""},
"Muster": {text: "Create two Recruit creatures with ! 1.", cost: 2, type: "Sorcery", power: ""},
"Mutual Confidence": {text: "You take a turn. Your opponent controls you during that turn. Then, your opponent takes a turn. You control them during that turn.", cost: 5, type: "Sorcery", power: ""},
"Mystery Box": {text: "Start of each Execution: X becomes the ! of this. Leave: Choose any number of Creature spells in your Archive. If their total $ is equal to X, create a copy of each of them.", cost: 2, type: "Creature", power: 0},
"Necroflickerer": {text: "Hits a player: Destroy all creatures you control, then return them to the battlefield.", cost: 6, type: "Creature", power: 3},
"Necrotrickster": {text: "When another creature dies, this becomes a copy of it.", cost: 2, type: "Creature", power: 1},
"Nether Guide": {text: "Start of each Execution: You may choose a creature you control with ! X, destroy that creature, choose a Creature spell with $ X+1 in your Void, and put it onto the Battlefield.", cost: 3, type: "Creature", power: 2},
"Night's Herald": {text: "Skip your Beginning phase. Start of your opponent's Execution: Take a Beginning phase.", cost: 5, type: "Creature", power: 4},
"Nightmare": {text: "Dies: Put this onto the Battlefield, then choose a creature and bind this to it.", cost: 9, type: "Creature", power: 7},
"Null Mage": {text: "The $s of Sorcery spells in Spellbooks are increased by 1.", cost: 2, type: "Creature", power: 2},
"Old General": {text: "The $s of Creature spells in your Spellbook are reduced by 1.", cost: 3, type: "Creature", power: 3},
"Old Wizard": {text: "The $s of Sorcery spells in your Spellbook are reduced by 1.", cost: 3, type: "Creature", power: 3},
"Omniscience": {text: "Put all spells in your Archive into your Spellbook.", cost: 8, type: "Sorcery", power: ""},
"Oppressor": {text: "Hits a player: Destroy two Attack actions in the Plan.", cost: 3, type: "Creature", power: 3},
"Patron": {text: "Start of your Execution: Distribute one mana.", cost: 2, type: "Creature", power: 1},
"People-hungry Rampager": {text: "When you Plan a Creature spell, you may bind it to this. End of each turn: If this damaged a player this turn, create a copy of all Creature spells bound to this.", cost: 2, type: "Creature", power: 1},
"Perfect Reflection": {text: "Each player creates a copy of each creature they control.", cost: 8, type: "Sorcery", power: ""},
"Persuade": {text: "Choose a creature and gain control of it.", cost: 8, type: "Sorcery", power: ""},
"Philosopher": {text: "When you Shift: Put a spell from your Archive into your Spellbook.", cost: 4, type: "Creature", power: 3},
"Plagiarize": {text: "Destroy all spells in your Archive, then put a copy of each spell in your opponent's Archive into your Archive.", cost: 5, type: "Sorcery", power: ""},
"Politician": {text: "Start of each Execution: Your opponent gains control of each other creature until end of turn. Then, choose a number. Gain control of each creature with ! equal to that number until end of turn.", cost: 2, type: "Creature", power: 2},
"Polymorph": {text: "Choose a creature and destroy it. Its controller creates a Ram creature with ! 4.", cost: 1, type: "Sorcery", power: ""},
"Possess": {text: "Choose a creature. You become that creature. (You control that creature and you are no longer attackable. That creature is now considered a player instead of a creature for spells and abilities, but is still a creature on the Battlefield otherwise and can attack, be attacked, and have mana distributed to it. When it dies, you lose the game.)", cost: 13, type: "Sorcery", power: ""},
"Possibility Marble": {text: "Choose a spell in your Archive and put it into your Spellbook. Take a Plan phase.", cost: 2, type: "Sorcery", power: ""},
"Possibility Seeker": {text: "Start of your Execution: Reduce your Shift by 1.", cost: 6, type: "Creature", power: 4},
"Protective Grace": {text: "The next time a creature you control dies this turn, put it onto the Battlefield.", cost: 2, type: "Sorcery", power: ""},
"Puissant Muse": {text: "Mana can't be distributed to this during your Distribute subphase. Start of your Execution: Distribute X mana, where X is the ! of this. Mana can't be distributed to this by this ability.", cost: 5, type: "Creature", power: 1},
"Punish": {text: "Choose one -  - Destroy all creatures with 3 or less !. - Destroy all creatures with 4 or more !.", cost: 5, type: "Sorcery", power: ""},
"Raging Demon": {text: "Start of each Execution: Deal 2 damage to yourself. Hits a player: Your opponent gains control of this.", cost: 3, type: "Creature", power: 4},
"Rally": {text: "Put three mana on each creature you control.", cost: 10, type: "Sorcery", power: ""},
"Raze": {text: "Destroy all creatures.", cost: 7, type: "Sorcery", power: ""},
"Reanimate": {text: "Choose a Creature spell in a Void and put it onto the Battlefield.", cost: 5, type: "Sorcery", power: ""},
"Reanimating Corpse": {text: "In your Void: Start of your Execution: You may remove two mana from a spell in your Spellbook and put this onto the Battlefield.", cost: 2, type: "Creature", power: 2},
"Rebirth": {text: "For each creature you control, choose a spell in your Void with the same name and put that spell into your Spellbook.", cost: 4, type: "Sorcery", power: ""},
"Rebuke": {text: "Choose a spell in the Plan. Its controller puts it into their Spellbook. Choose a spell in your Archive and put it into your Spellbook.", cost: 3, type: "Sorcery", power: ""},
"Recall": {text: "Choose a spell in your Void and put it into your Spellbook.", cost: 3, type: "Sorcery", power: ""},
"Reclusive Witch": {text: "Enter: Bind all creatures to this. For each creature bound this way, its controller creates a Ram creature with ! 4. Leave: Destroy all Rams.", cost: 8, type: "Creature", power: 5},
"Recollect": {text: "Choose two spells in your Void and put them into your Archive.", cost: 3, type: "Sorcery", power: ""},
"Recruit": {text: "", cost: 0, type: "Creature", power: 1},
"Recruiter": {text: "Start of your Execution: Create a Recruit creature with ! 1.", cost: 3, type: "Creature", power: 1},
"Recycle Mage": {text: "When a spell would be put into a player's Void, put that spell into their opponent's Spellbook instead.", cost: 8, type: "Creature", power: 6},
"Red Phoenix": {text: 'Dies: Put this onto the battlefield, create a Red Phoenix Egg with ! 1 and "This cannot attack", then bind this to it.', cost: 6, type: "Creature", power: 6},
"Refleshment Vendor": {text: "End of your turn: Choose a creature that died this turn and create a copy of it. Leave: Destroy any creatures created by this.", cost: 7, type: "Creature", power: 4},
"Reinterpret": {text: "Choose a spell in the Plan and put a copy of it into your Spellbook.", cost: 2, type: "Sorcery", power: ""},
"Relentless Berserker": {text: "When damage is dealt, put one mana on this.", cost: 3, type: "Creature", power: 1},
"Reminisce": {text: "Put all spells in your Void into your Archive.", cost: 6, type: "Sorcery", power: ""},
"Ritual Cultist": {text: "Dies: Distribute seven mana.", cost: 5, type: "Creature", power: 1},
"Rune of Mana": {text: "Choose a creature and bind this to it. When this is bound to a creature: Put two mana on that creature.", cost: 4, type: "Sorcery", power: ""},
"Salvage Memories": {text: "Choose X spells in your Archive and destroy them. For each spell destroyed this way, choose X spells in your Void and put each of them into your Spellbook.", cost: "XX", type: "Sorcery", power: ""},
"Sculpt": {text: "Create a copy of a creature you control with X-2 mana on it. X must be at least 2.", cost: "X", type: "Sorcery", power: ""},
"Senator": {text: "Enter: Bind a spell from your Archive to this, then bind all spells with the same $ from your opponent's Archive to this.", cost: 2, type: "Creature", power: 2},
"Sentry": {text: "Start of each Execution: Choose a number.  Creatures with ! equal to the last chosen number don't deal damage.", cost: 4, type: "Creature", power: 4},
"Severe Teacher": {text: "Start of your Execution: If your opponent has no spells in their Spellbook, put two mana on this.", cost: 1, type: "Creature", power: 1},
"Shadow Serpent": {text: "In your Spellbook: The $ of this is decreased by 1 for each exhausted creature on the Battlefield.", cost: 7, type: "Creature", power: 7},
"Shadow of Life": {text: "Start of each Execution: If your life total is equal to 8, deal 1 damage to yourself and put eight mana on this.", cost: 1, type: "Creature", power: 1},
"Shadow of Magic": {text: "Start of each Execution: The amount of mana on this becomes equal to X, where X is the number of spells in Voids.", cost: 1, type: "Creature", power: 1},
"Shapeshifter": {text: "Start of each Execution: Choose a Creature spell in a Void with $ X, where X is the ! of this. This becomes a copy of it until end of turn.", cost: 1, type: "Creature", power: 1},
"Share Secrets": {text: "Choose two spells in your Archive and put them into your Spellbook. Then, your opponent chooses a spell in your Archive and puts it into their Spellbook.", cost: 1, type: "Sorcery", power: ""},
"Shield": {text: "Choose a creature or player. They can't be damaged or destroyed this turn.", cost: 1, type: "Sorcery", power: ""},
"Silencer": {text: "Other creatures have no abilities.", cost: 3, type: "Creature", power: 3},
"Siren Song": {text: "Choose a creature you control. Exhaust each creature you don't control and they each attack that creature (in any order).", cost: 3, type: "Sorcery", power: ""},
"Snappy Salvager": {text: "End of each turn: If this damaged a player this turn, choose a Sorcery spell in a Void and copy its effects.", cost: 6, type: "Creature", power: 4},
"Snappy Witch": {text: "Start of each Execution: X becomes the ! of this. Leave: Choose any number of Sorcery spells in your Void. If their total $ is equal to X, copy their effects in any order.", cost: 2, type: "Creature", power: 0},
"Soldier": {text: "", cost: 2, type: "Creature", power: 3},
"Spell Serpent": {text: "In your Spellbook: The $ of this is reduced by 1 for each Sorcery spell in your Void.", cost: 7, type: "Creature", power: 7},
"Star": {text: "When this is chosen by a spell or ability, put two mana on this.", cost: 3, type: "Creature", power: 2},
"Starstorm": {text: "For each action in the Plan, choose a creature or player and deal 1 damage to them.", cost: 7, type: "Sorcery", power: ""},
"Statue of the Hero": {text: "This can't attack. Start of your Execution: Put two mana on each other creature you control.", cost: 7, type: "Creature", power: 4},
"Statue of the Rabbit-Lord": {text: "This can't attack. Start of your Execution: Create a Little Bunny creature with ! 1.", cost: 4, type: "Creature", power: 4},
"Stitched Abomination": {text: "Enter: Bind all Creature spells in your Void to this. When this takes damage, choose a Creature spell bound to this with $ X, where X is the damage dealt, and put it onto the Battlefield.", cost: 8, type: "Creature", power: 6},
"Strike": {text: "Choose a creature you control. It attacks. (You don't need to exhaust the creature.)", cost: 2, type: "Sorcery", power: ""},
"Sun's Disdain": {text: "If it's your turn, choose a spell in the Plan and put it into its owner's Archive.", cost: 1, type: "Sorcery", power: ""},
"Sun's Revenge": {text: "Choose an unexhausted creature and destroy it.", cost: 2, type: "Sorcery", power: ""},
"Sun's Wrath": {text: "Destroy all unexhausted creatures.", cost: 4, type: "Sorcery", power: ""},
"Support": {text: "Exhaust any number of creatures you control. For each creature exhausted this way, distribute one mana.", cost: 4, type: "Sorcery", power: ""},
"Swindle": {text: "Choose a creature you control and a creature you don't control. Exchange control of them.", cost: 6, type: "Sorcery", power: ""},
"Tax": {text: "Choose X creatures you control and destroy them. If you do, your opponent chooses X creatures they control and destroys them.", cost: "XX", type: "Sorcery", power: ""},
"Teacher of Humility": {text: "Start of your Execution: Each creature's ! becomes 1.", cost: 3, type: "Creature", power: 1},
"Tempestuous Muse": {text: "When you Shift: Distribute four mana.", cost: 4, type: "Creature", power: 2},
"Thematic Idea": {text: "Distribute one mana for each spell in your Void with the same name as this.", cost: 1, type: "Sorcery", power: ""},
"Thief's Wish": {text: "Choose a Sorcery spell with $ X in your opponent's Archive and copy its effects.", cost: "X", type: "Sorcery", power: ""},
"Think Thrice": {text: "Choose three spells in your Archive and put them into your Spellbook.", cost: 6, type: "Sorcery", power: ""},
"Think Twice": {text: "Choose two spells in your Archive and put them into your Spellbook.", cost: 3, type: "Sorcery", power: ""},
"Think": {text: "Choose a spell in your Archive and put it into your Spellbook.", cost: 1, type: "Sorcery", power: ""},
"Thought Thief": {text: "Hits a player: Choose a spell from that player's Archive and bind it to this.", cost: 3, type: "Creature", power: 3},
"Thought Twist": {text: "Each player swaps all spells in their Spellbook with all spells in their Archive.", cost: 4, type: "Sorcery", power: ""},
"Thoughtsculpt": {text: "Your opponent divides all spells in Voids into two piles face up. Choose a pile and put all spells in that Pile into their owners' Spellbooks.", cost: 4, type: "Sorcery", power: ""},
"Thunderbolt": {text: "Choose a creature or player. Deal 3 damage to them.", cost: 3, type: "Sorcery", power: ""},
"Thunderbound Demon": {text: "Start of your Execution: Choose a creature you control and deal 3 damage to it.", cost: 3, type: "Creature", power: 6},
"Thunderstorm": {text: "Choose three different creatures and/or players. Deal 3 damage to them.", cost: 7, type: "Sorcery", power: ""},
"Time Stop": {text: "End the turn. (Destroy all spells and Attack actions in the Plan.)", cost: 8, type: "Sorcery", power: ""},
"Time Warp": {text: "Take a turn.", cost: 13, type: "Sorcery", power: ""},
"Tradewinds": {text: "Choose a creature you control and put it into your Spellbook. If you do, choose a creature you don't control. Its owner puts it into their Spellbook.", cost: 1, type: "Sorcery", power: ""},
"Tragic Romance": {text: "Choose two creatures. When one dies this turn, destroy the other.", cost: 1, type: "Sorcery", power: ""},
"Tranquility Mage": {text: "Start of each Execution: The player who doesn't control the last spell in the Plan puts a spell from their Archive into their Spellbook.", cost: 5, type: "Creature", power: 5},
"Trickster": {text: "When you Plan a spell, choose a creature. This becomes a copy of it until end of turn, except it gains this ability.", cost: 2, type: "Creature", power: 2},
"Trinimancer": {text: "Leave: The amount of mana on each other creature becomes 3.", cost: 3, type: "Creature", power: 3},
"Troll": {text: "Start of each Execution: Your opponent creates two Recruit creatures with ! 1.", cost: 4, type: "Creature", power: 8},
"Twee Fwogs": {text: "Create three Frog creatures with ! 1.", cost: 3, type: "Sorcery", power: ""},
"Twist Motives": {text: "Choose a creature and gain control of it until end of turn. It attacks. (You don't need to exhaust the creature.)", cost: 3, type: "Sorcery", power: ""},
"Ultimate Challenge": {text: "Each player chooses a creature they control. Destroy all other creatures.", cost: 3, type: "Sorcery", power: ""},
"Ultranecromancer": {text: "Hits a player: Put all creature spells that were put into a Void this turn onto the Battlefield under your control.", cost: 7, type: "Creature", power: 4},
"Unchosen One": {text: "This can't be chosen by spells or abilities (while on the Battlefield).", cost: 4, type: "Creature", power: 4},
"Unending Shelves": {text: "Choose X spells in the Plan and put a copy of each of them into your Archive.", cost: "XX", type: "Sorcery", power: ""},
"Unleash Creations": {text: "Choose a creature spell in your Archive with $ 1, a creature spell in your Archive with $ 2, a creature spell in your Archive with $ 3, and a creature spell in your Archive with $ 4. Create a copy of each.", cost: 8, type: "Sorcery", power: ""},
"Unleash Knowledge": {text: "Choose a Sorcery spell in your Archive with $ 1, a Sorcery spell in your Archive with $ 2, a Sorcery spell in your Archive with $ 3, and a Sorcery spell in your Archive with $ 4. Copy each of their effects in any order.", cost: 8, type: "Sorcery", power: ""},
"Utilitarimance": {text: "Put all creature spells from your Void to the Battlefield, then for each creature returned this way, choose a creature you control and destroy it.", cost: 9, type: "Sorcery", power: ""},
"Utilitarimancer": {text: "When another creature you control would die, instead destroy that creature, put that creature onto the battlefield, then choose a creature you control and destroy it. (Replacement effects don't trigger themselves.)", cost: 8, type: "Creature", power: 4},
"Vampire": {text: "Hits a creature: You gain life equal to the ! of this.", cost: 4, type: "Creature", power: 4},
"Vampiric Creativity": {text: "Distribute X mana, where X is 8 minus your life total.", cost: 2, type: "Sorcery", power: ""},
"Vampiric Mathemagic": {text: "Deal 4 damage to your opponent. You gain 4 life. In your Void: Start of each Execution: If your life total is equal to 8, put this into your Spellbook.", cost: 4, type: "Sorcery", power: ""},
"Vampiric Undeath": {text: "You gain 14 life. In your Spellbook: You don't lose the game for having 0 or less life. As long as you have 0 or less life, damage dealt to you puts that much mana on this instead. When there is 8 or more mana on this, you lose the game.", cost: 7, type: "Sorcery", power: ""},
"Veil Mage": {text: "Start of each Execution: Each player chooses a spell in their Archive and binds it to this.", cost: 2, type: "Creature", power: 2},
"Vengeful Berseker": {text: "When damage is dealt to this, choose a creature or player and deal that much damage to them.", cost: 5, type: "Creature", power: 4},
"Vengeful Watchman": {text: "Dies: Choose an exhausted creature and destroy it.", cost: 2, type: "Creature", power: 2},
"Viper": {text: "When this deals damage to a creature, destroy that creature.", cost: 3, type: "Creature", power: 2},
"Vulture": {text: "When another creature dies, put one mana on this.", cost: 1, type: "Creature", power: 1},
"Watchman": {text: "End of your turn: Choose a creature you control and unexhaust that creature.", cost: 5, type: "Creature", power: 5},
"White Phoenix Egg": {text: "This can't attack. Dies: Put this onto the battlefield, create a White Phoenix with ! 6, and bind this to it.", cost: 4, type: "Creature", power: 1},
"Wild Imagination": {text: "Choose three different Sorcery spells in your Archive with total $ X-3 and copy their effects sequentially.", cost: "X", type: "Sorcery", power: ""},
"Wild Mage": {text: "End of your turn: Choose a spell with $ X in your Archive, where X is the ! of this. Put it into the Plan.", cost: 2, type: "Creature", power: 0},
"Will-o'-the-wisps": {text: "Create three Ghost creatures with ! 0.", cost: 0, type: "Sorcery", power: ""},
"Wish": {text: "Choose a Sorcery spell with $ X-1 in your Archive and copy its effects.", cost: "X", type: "Sorcery", power: ""},
"Young General": {text: "When you Plan another Creature spell, put one mana on this.", cost: 2, type: "Creature", power: 2},
"Young Wizard": {text: "When you Plan a Sorcery spell, put one mana on this.", cost: 2, type: "Creature", power: 2},
"Zombie Lemming": {text: "In your Void: When another Creature spell in your Void is placed into another zone, put this into that zone.", cost: 3, type: "Creature", power: 3}};
var cardnames = [];
for (i in allcards) {
    cardnames.push(i);
}
